### ISSUE TITLE
KeyError: 'deadlineDate' when creating League object

### ISSUE THREAD

**Issue by OD1995** [cwendt94/ff-espn-api#10]
Attempting to follow this example code:

```
from ff_espn_api import League
league_id = 1234
year = 2018
swid = '{03JFJHW-FWFWF-044G}'
espn_s2 = 'ASCWDWheghjwwqfwjqhgjkjgegkje'
league = League(league_id, year, espn_s2, swid)
```

I got this error:

```

  File "<ipython-input-26-f3f7b9b05a45>", line 6, in <module>
    league = League(league_id, year, espn_s2, swid)

  File "C:\Users\Oli\AppData\Local\Continuum\anaconda3\lib\site-packages\ff_espn_api\league.py", line 49, in __init__
    self._fetch_league()

  File "C:\Users\Oli\AppData\Local\Continuum\anaconda3\lib\site-packages\ff_espn_api\league.py", line 69, in _fetch_league
    self._fetch_settings()

  File "C:\Users\Oli\AppData\Local\Continuum\anaconda3\lib\site-packages\ff_espn_api\league.py", line 145, in _fetch_settings
    self.settings = Settings(data['settings'])

  File "C:\Users\Oli\AppData\Local\Continuum\anaconda3\lib\site-packages\ff_espn_api\settings.py", line 9, in __init__
    self.trade_deadline = data['tradeSettings']['deadlineDate']

KeyError: 'deadlineDate'
```

I'm pretty confident I've got the correct `swid` and `espn_s2` values for my league, although my `espn_s2` is 300 characters long compared to the example one with 29 characters..

**Comment by cwendt94** [comment]
Hi @OD1995 you swid and espn_s2 are correct else it would have thrown a access denied error. This bug looks like ESPN does not send a deadlineDate field if it is not set in the league. This should be an easy fix. Thank you for reporting this!

**Comment by cwendt94** [comment]
I added the fix and tested it. I am going to push a new version of ff_espn_api. Let me know if you run into anymore errors.

**Comment by kevenrc** [comment]
I ran into a similar error that says KeyError: 'owners' when trying to create League object.

**Comment by OD1995** [comment]
@cwendt94 Great, all fixed, thanks!

**Comment by cwendt94** [comment]
@kevenrc Interesting so you are getting a key error for 'owners'? I will look into that. I would think owners key would always be in the data.

**Comment by kevenrc** [comment]
@cwendt94 could it be because I am trying to create the League object on a league that hasn't had a draft yet?

**Comment by cwendt94** [comment]
I don't believe so because I can access my 2019 league. Is this a brand new league this year?

**Comment by kevenrc** [comment]
@cwendt94 Yes, it's a brand new league this year.

**Comment by cwendt94** [comment]
Interesting, I am guessing with brand new leagues owners field is not given. I will look into this and come up with a fix!

**Comment by dtcarls** [comment]
Is the league full? This was a bug with espn_ff.

**Comment by cwendt94** [comment]
@kevenrc The newest package should work if a team does not have a owner! Let me know if it fixes it and that there is not any other errors!
