### ISSUE TITLE
POSITION_MAP[pos] KeyError: 25

### ISSUE THREAD

**Issue by harry19023** [cwendt94/ff-espn-api#16]
When creating a league player.py throws a KeyError:

```
File "C:\********\packages\ff_espn_api\player.py", line 18, in __init__
    if '/' not in POSITION_MAP[pos] or '/' in self.name:
KeyError: 25
```

**Comment by harry19023** [comment]
I found the offending player: 
player['fullName']: T.J. Hockenson
player['eligibleSlots']: [25, 5, 6, 23, 7, 20, 21]

**Comment by cwendt94** [comment]
Interesting. He is a TE and I haven't seen 25 as a eligible slot before. What slots can you position T.J. Hockenson in your league?

**Comment by harry19023** [comment]
He's a normal TE as far as I can tell. We don't have any odd positions turned on either...

![image](https://user-images.githubusercontent.com/8812828/62981802-15a4f680-bddf-11e9-8f2d-92d488f34081.png)


![image](https://user-images.githubusercontent.com/8812828/62981816-22c1e580-bddf-11e9-8323-98015b12c222.png)

**Comment by cwendt94** [comment]
I think slot id 24 is Edge Rusher which is new in the past two years. I am still trying to find what 25 could be for offensive players

**Comment by cwendt94** [comment]
Actually it looks like its both offensive positions and defensive positions. I think it might be a ID for Rookies. All the players I see that have slot id 25 are rookies.

**Comment by cwendt94** [comment]
Newest package should have the fix @harry19023

**Comment by harry19023** [comment]
It works, thanks!
