### ISSUE TITLE
Implement Free Agency List

### ISSUE THREAD

**Issue by rhartman93** [cwendt94/ff-espn-api#18]
For a given week, be able to get a list of players on free agency, similar to box player, slot_position could be 'FA'

**Comment by rhartman93** [comment]
Are you looking at docs for the api? I've been trying to find something to reference to try and find the proper endpoints , etc. This project has some free agency info: https://github.com/mkreiser/ESPN-Fantasy-Football-API but I'm not as familiar with javascript so having a hard time parsing out what they're doing

**Comment by cwendt94** [comment]
ESPN doesn't document their API at all. I use chrome dev tools and basically see what requests their app and website make to the backend api. Also I think I see how to get free agents. However it only looks like you can get the current season free agents and not past seasons..

**Comment by rhartman93** [comment]
I think you can pass a scoringPeriodId, although I'm not exactly sure what the proper use of that parameter is, I see you used 0 in fetch_players. Without setting it though I did get back basically the entire NFL so I'm assuming like you said that's this year's free agency since my league hasn't drafted yet

**Comment by rhartman93** [comment]
Although I think even getting it for the current year has utility, it just would need to be documented as such

**Comment by cwendt94** [comment]
Yeah, I am playing around with the scoringPeriodId for 2018 season and when looking through all the players it is showing how the rosters were at the end of the season. Even if I put scoringPeriodId=2 it shows players that my team had at the end of the season.

**Comment by cwendt94** [comment]
Definitely! I like the idea of being able to see what players are on free agency! I can probably have this feature done by the end of tomorrow.

**Comment by cwendt94** [comment]
Free agency feature is now in the latest package!

**Comment by rhartman93** [comment]
This looks great, I'll test it out tonight

**Comment by cwendt94** [comment]
Sounds good! Also I just found out a way that we can pass filters to order the free agents and set limits on how many free agents you want to see!

**Comment by rhartman93** [comment]
Oh that would be great, I'd imagine sorting by scored points would be super useful

**Comment by cwendt94** [comment]
Yeah, without the filters it seems like it shows free agents all the way at the bottom first.

**Comment by cwendt94** [comment]
Filtering is also in the latest package!
