### ISSUE TITLE
KeyError: 'pointsByScoringPeriod'

### ISSUE THREAD

**Issue by cdgarren** [cwendt94/ff-espn-api#26]
I'm running into the following error when using the League.box_scores function for 2019 Week 1:
```
  File "/home/cdgarren/Projects/fantasyfootball/env/lib/python3.5/site-packages/ff_espn_api/league.py", line 309, in box_scores
    box_data = [BoxScore(matchup) for matchup in schedule if str(week) in matchup['home']['pointsByScoringPeriod']]
  File "/home/cdgarren/Projects/fantasyfootball/env/lib/python3.5/site-packages/ff_espn_api/league.py", line 309, in <listcomp>
    box_data = [BoxScore(matchup) for matchup in schedule if str(week) in matchup['home']['pointsByScoringPeriod']]
KeyError: 'pointsByScoringPeriod'
```

I'm working on migrating my homebrew scripts to use your module, and I was able to recreate what I needed while testing with the 2018 season. This occurs when I switch to 2019. So I'm not sure if this is stemming from an API change, or if this is due to the fact that the games for the Week 1 haven't started yet.

**Comment by cwendt94** [comment]
I recently updated the package to fix this error. Try updating and let me know if it is fixed!

**Comment by cdgarren** [comment]
That did fix it. Thanks!
