### ISSUE TITLE
Feature Request: Add decimal places to the Box Score projections

### ISSUE THREAD

**Issue by Jsayer7** [cwendt94/ff-espn-api#30]
Great work on the python API, it's really great. I'm in a league that does 0.1 points per yard for RB/WR/TE, and 0.04 points per yard thrown for QB. This causes the projections and scores to be translated as doubles, not straight integers. I noticed that the box_scores projections don't have decimal places. It would be nice if it did for leagues similar to ours.

**Comment by dtcarls** [comment]
They are provided as decimals on a per player basis.

**Comment by cwendt94** [comment]
I updated box_scores yesterday and I believe the scores and players points should be 2 decimal places if the league has them. The newest package version is 1.1.0

**Comment by Jsayer7** [comment]
Ah, I cloned prior to that. I'll check it out and see. Thanks guys

**Comment by cwendt94** [comment]
Sounds good, let me know if you still have problems!
