### ISSUE TITLE
Feature Request: Starter/Bench parameter for BoxPlayer

### ISSUE THREAD

**Issue by aaronst** [cwendt94/ff-espn-api#31]
First off, thanks for making this, really awesome stuff.

It would be cool if there was a parameter on each `BoxPlayer` denoting whether they were a starter or on the bench for the given week.

**Comment by aaronst** [comment]
Better yet, it'd be great to see what each team's starting lineup was. Even if that means a position was empty.

**Comment by dtcarls** [comment]
box_player.slot_position determines the player's current spot. "BE" denotes bench. You can iterate through each player and do logic based on slot_position to determine starting lineup

**Comment by aaronst** [comment]
Ah, got it. That works, thanks!
