### ISSUE TITLE
Randomly Inflated scores?

### ISSUE THREAD

**Issue by dtcarls** [cwendt94/ff-espn-api#34]
I have some users reporting seemingly random scores inflated by up to 16 points. I am using the home_score and away_score variables from box_scores to pull this information. See some troubleshooting data here.
https://github.com/dtcarls/fantasy_football_chat_bot/issues/44

**Comment by cwendt94** [comment]
I looked at the endpoint for my league and all the numbers are lining up for me. It seems really weird that a couple scores in a league would be wrong and not all of them.

**Comment by bnm91** [comment]
I'm also seeing this.  I'm the Commisioner of the league in question.  If anyone figures this out I'd appreciate it.

![image](https://user-images.githubusercontent.com/19519681/64588086-34eb6100-d356-11e9-8545-645a0a2769a2.png)

**Comment by cwendt94** [comment]
If you could attach that endpoints data in a text file and tell me the final scores for each team I can try to do some debugging tomorrow

**Comment by bnm91** [comment]
Kind of convinced now it's an ESPN issue.  They're having a bunch of other problems on the scoreboard page right now (scores not loading, defaulting to wrong week, discrepancy between box score and scoreboard views).  

Will report back if the issue doesn't resolve itself tomorrow.

**Comment by bnm91** [comment]
Works this morning.  I wonder if it's the same for @dtcarls

**Comment by cwendt94** [comment]
Interesting, I did see ESPN pushed a critical update for their App this morning. Maybe it has some connection with the scores being weird?? Hopefully it is all good now

**Comment by dtcarls** [comment]
I personally haven't had an issue, but I'm standing by to hear from my user base to see if the problem persists.
