### ISSUE TITLE
Exception: Access denied

### ISSUE THREAD

**Issue by bluesforsalvador** [cwendt94/ff-espn-api#36]
I'm getting this access denied error when I try to set up the variable "League"
I'm sure it's something simple.  I'm in Windows.

Can anyone help?
Thanks,

```
from ff_espn_api import League
import numpy as np

league_id = 88888
year = 2019
league = League(league_id, year)

```
![image](https://user-images.githubusercontent.com/2042613/64657279-b3044200-d400-11e9-8a4c-c6d5fb2e4a98.png)

**Comment by dtcarls** [comment]
Is your league private? You will need to set swid and espn_s2 in league
initialization or make your league public.

**Comment by bluesforsalvador** [comment]
ahhh, weird...I thought my league was public, but apparently it was private...that fixed my access issue...thanks!
