### ISSUE TITLE
"filterSlotIds":{"value":slot_filter} | free_agents

### ISSUE THREAD

**Issue by rysull23** [cwendt94/ff-espn-api#40]
In the free_agents method, the "filterSlotIds" filter is causing the following error message from the ESPN API. Irrespective of the value provided in that field. Are you seeing the same?

{'cause': 'Cannot deserialize instance of `java.util.ArrayList` out of VALUE_STRING token\n at [Source: (String)"{"players": {"filterStatus": {"value": ["FREEAGENT", "WAIVERS"]}, "filterInjured": {"value": "false"}, "filterSlotIds": {"value": slot_filter}, "limit": 50, "sortPercOwned": {"sortPriority": 1, "sortAsc": false}, "sortDraftRanks": {"sortPriority": 100, "sortAsc": true, "value": "STANDARD"}}, "communication": {"topicsByType": {}}}"; line: 1, column: 131] (through reference chain: com.espn.fantasy.lm.filter.LeagueApiFilter$LeagueFilterParams["players"]->com.espn.fantasy.lm.filter.PlayerPoolEntryFilter$PlayerPoolFilterParams["filterSlotIds"]->com.espn.fantasy.lm.filter.ApiFilter$ParamValue["value"])',
 'messages': ["Invalid parameter for 'LeagueFilterParams'."]}

**Comment by cwendt94** [comment]
I ran free_agents method with my league and I didn't get any errors with ESPN API. You are seeing this error with your league?

**Comment by rysull23** [comment]
resolved.
