### ISSUE TITLE
Data on opponents in box_player

### ISSUE THREAD

**Issue by gayverjr** [cwendt94/ff-espn-api#43]
Would it be reasonable/doable for the box_player class to store the name and OPRK of the player's opponent that week?

**Comment by cwendt94** [comment]
By players opponent do you mean the others teams player in the same position?

**Comment by gayverjr** [comment]
Wow sorry that was really unclear. I meant real life life opponent. So for this week for example, I would want to know that Saquon Barkley is playing the Bills defense, who is ranked 15th against RBs this season.

**Comment by cwendt94** [comment]
Gotcha! That would be really good data! Let me look at the API and see if I can find out what endpoint that data comes from
