### ISSUE TITLE
Get player's score for a certain week

### ISSUE THREAD

**Issue by DesiPilla** [cwendt94/ff-espn-api#45]
When using the parameter `{'scoringPeriodId': 2}` to fetch stats for a given week, the player's score is returned as the player's season total, not his weekly total. When the `scoringPeriodId` parameter is not used, the current week's stats are collected and the current points for a player is his weekly total. How can I get a weekly total for a week that has already passed?

```python
>> matchups = requests.get(url, cookies = cookies, params = {'view' : 'mMatchup', 'scoringPeriodId': 2}).json()
# See Lamar Jackson's stats for week 2
>> matchups['teams'][0]['roster']['entries'][16]['playerPoolEntry']['appliedStatTotal']
64.44
# 64.44 is his season total, not his weekly total
```

**Comment by cwendt94** [comment]
Check out the the "schedule" object instead of "teams" object.

Like
```python
>> matchups = requests.get(url, cookies = cookies, params = {'view' : 'mMatchup', 'scoringPeriodId': 2}).json()
>> matchups['schedule'][0]['away']['rosterForCurrentScoringPeriod']['entries']...
```

**Comment by DesiPilla** [comment]
I tried this but it does the same thing.

**Comment by cwendt94** [comment]
Interesting, I just tried it out on my league and was able to get week 1s player score using the same endpoint. In the schedule object make sure you go to the correct scoring period you want to look at. It should have more fields and under “rosterForCurrentScoringPeriod”.

Could you show me how you are accessing the object returned from the API?

**Comment by DesiPilla** [comment]
The `rosterForCurrentScoringPeriod` option isn't showing up for me.
```python
>>> matchups = requests.get(url, cookies = cookies, params = {'view' : 'mMatchup', 'scoringPeriodId': 2}).json()
>>> matchups['schedule'][0]['away'].keys()
dict_keys(['cumulativeScore', 'gamesPlayed', 'pointsByScoringPeriod', 'teamId', 'totalPoints'])
>>> matchups['schedule'][0]['away']['rosterforCurrentScoringPeriod']
Traceback (most recent call last):
  Python Shell, prompt 7, line 1
builtins.KeyError: 'rosterForCurrentScoringPeriod'
```

**Comment by cwendt94** [comment]
Try adding “view”: “mMatchupScore” to params for the request.

**Comment by DesiPilla** [comment]
It didn't change anything.
```python
>>> matchups = requests.get(url, cookies = cookies, params = { 'scoringPeriodId': 2, 'view' : 'mMatchupScore'}).json()
>>> matchups['schedule'][0]['away'].keys()
dict_keys(['adjustment', 'cumulativeScore', 'teamId', 'tiebreak', 'totalPoints'])
```

**Comment by cwendt94** [comment]
I think I might know the problem. If you are passing scoringPeriodId=2 then you will have to start “schedule” index at 5 if you want the first matchup in week two for a 10 man league.

**Comment by DesiPilla** [comment]
So using this method I am able to get the weekly score, but a lot of other data is missing in this structure. Previously, I was able to get the player's name, playerId, acquisitionType, eligibleSlots, injuryStatus, and a couple of other metrics. Here, there are far fewer attributes.

```python
>>> p = matchups['schedule'][5]['away']['rosterForCurrentScoringPeriod']['entries'][1]
>>> p.keys()
dict_keys(['lineupSlotId', 'playerPoolEntry'])
>>> p = p['playerPoolEntry']
>>> p.keys()
dict_keys(['player'])
>>> p = p['player']
>>> p.keys()
dict_keys(['stats'])
>>> p = p['stats']           # This is a list with two identical structures, but with different values
>>> p[0].keys()
dict_keys(['appliedStats', 'appliedTotal', 'proTeamId', 'scoringPeriodId', 'seasonId', 'statSourceId', 'statSplitTypeId', 'stats', 'variance'])
>>> p[1].keys()
dict_keys(['appliedStats', 'appliedTotal', 'proTeamId', 'scoringPeriodId', 'seasonId', 'statSourceId', 'statSplitTypeId', 'stats', 'variance'])
```
I don't know what the difference is in the final two lists. I have found that when week 1 is the `scoringPeriodId` then the 0 index has the correct score, and when week 2 is the `scoringPeriodId` then the 1 index has the correct score, but in both weeks there are exactly 2 elements in the list. Also, I am not able to get the players id or name anywhere.

**Comment by cwendt94** [comment]
If you checkout how box_scores() function works in league.py and follow that all the way through that should be able to help with some of those questions. In that function call I pass view=mMatchup and view=mMatchupScore to the ESPN API that will give you all of the player data with it.

**Comment by DesiPilla** [comment]
Yes thats it! Having both `'view' : 'mMatchupScore'` and `'view' : 'mMatchup'` (and weirdly it has to be in that order) solved all my issues! Just curious, how do you know what all of the possible parameters are? Is there a way to see all callable parameters?

**Comment by cwendt94** [comment]
That's good to hear! Unfortunately there is no easy way to find the different ESPN API endpoints and params. I watch the network calls from the ESPN website and see what API endpoints and the parameters are passed.

**Comment by rysull23** [comment]
Just reading through this...I think I found a player's total season fantasy points like this:

```
ENDPOINT = "https://fantasy.espn.com/apis/v3/games/FFL/seasons/" + str(year) + "/segments/0/leagues/" + str(league_id)

params = {
    'view': 'mRoster',
}
r = requests.get(ENDPOINT, params=params, cookies=cookies)

data = r.json()
data['teams'][6]['roster']['entries'][1]['playerPoolEntry']['ratings']['0']
```

This example is Nick Chubb: 
{'positionalRanking': 11, 'totalRanking': 58, 'totalRating': 49.399998}

<img width="1226" alt="Screen Shot 2019-09-26 at 10 32 44 PM" src="https://user-images.githubusercontent.com/31132172/65737803-bc063c00-e0ad-11e9-9acc-ac6cb14d1a1c.png">

I validated against another player, as well. Hope it helps.
