### ISSUE TITLE
KeyError: 'away' on box scores

### ISSUE THREAD

**Issue by johnmikep** [cwendt94/ff-espn-api#50]
This may very well be pebkac but when I try to pull any box scores I get a KeyError. I can pull other league settings without issue but it seems to break at this point. 

Something like the following will throw the following error:
box_scores = league.box_scores()
print (box_scores)

`Traceback (most recent call last):
  File "test.py", line 9, in <module>
    box_scores = league.box_scores(week=3)
  File "/Users/john.peterson/Documents/FF/venv/lib/python3.7/site-packages/ff_espn_api/league.py", line 313, in box_scores
    box_data = [BoxScore(matchup) for matchup in schedule]
  File "/Users/john.peterson/Documents/FF/venv/lib/python3.7/site-packages/ff_espn_api/league.py", line 313, in <listcomp>
    box_data = [BoxScore(matchup) for matchup in schedule]
  File "/Users/john.peterson/Documents/FF/venv/lib/python3.7/site-packages/ff_espn_api/box_score.py", line 8, in __init__
    self.away_team = data['away']['teamId']
KeyError: 'away'`

Is there a way to just pull the league data object to parse and see if it is being returned in a different structure? Fwiw its a private league. 

Thank you for putting this together, its wonderful.

**Comment by cwendt94** [comment]
At the moment there is no way to see the box_score data without calling the ESPN API in your own browser. I think that I should add a feature to have a “logger mode” that would print out all of the json returned from API calls. This would make it really easy to debug.

For the error your running into that’s interesting that there isn’t a away team. Do you have bye weeks in your league? Also could you try passing box_scores(week=1) or week=2, to see if that gives you a error.

**Comment by johnmikep** [comment]
I forgot to mention that I had tried with week= as well, but it yields the same KeyError. 
We do have a bye week because we ended up with an odd number of players. 
Question: it shouldn't matter if I am the league owner or not to pull the data correct?

**Comment by cwendt94** [comment]
Okay that is good to know about the bye week! It’s hard knowing what ESPN API does with different league settings. I will also try to look at it later and see if I can come up with a solution.

**Comment by markten** [comment]
I ran into a similar issue yesterday while trying to pull all team scores from the last 7 years of data in the league I participate in. I was iterating over years and weeks pulling scoreboard and box_score data. In my case it was requests for playoff weeks failing and as a result, the matchup object was failing to init the dict.

I independently went with a fail->log->continue solution similar to what @johnmikep did. I think it's a reasonable approach since you can go back and look at the gaps to figure out why the request may have come up with nothing.

**Comment by cwendt94** [comment]
Yeah the biggest help for debugging is the json that is returned from the ESPN API. The continue could get a little tricky as some of the calls rely on that data later down for processing.

Where did it fail for playoffs? I know playoffs can be a little tricky as matchup period and scoring period can differ with same matchup span multiple scoring periods.

**Comment by dhellfeld** [comment]
Box score is fixed, but this issue still remains with scoreboard
