### ISSUE TITLE
Datetime Format?

### ISSUE THREAD

**Issue by rysull23** [cwendt94/ff-espn-api#55]
Do you know what Date-time format is being used by the API? My goal is to pull transactions for the past week.  For example, in Recent-Activity...

import datetime
thyme = data[8]['messages'][0]['date']
datetime.datetime.fromtimestamp(thyme).strftime('%c')
--> 'Mon Jan  2 22:24:11 51708'

import time
time.localtime(thyme)
--> time.struct_time(tm_year=51708, tm_mon=1, tm_mday=2, tm_hour=22, tm_min=24, tm_sec=11, tm_wday=0, tm_yday=2, tm_isdst=0)

**Comment by cwendt94** [comment]
Yeah it uses epoch time in milliseconds

**Comment by rysull23** [comment]
awesome. got it. thanks. 

seems like the bounds on that api search are roughly the season start/end dates?

**Comment by cwendt94** [comment]
Exactly, I wanted to open it up wide so if anyone wants to make the size really large they would be able to get all of the activity.

**Comment by rysull23** [comment]
cool. thank you.
