### ISSUE TITLE
Feature request: box scores

### ISSUE THREAD

**Issue by ButteredGroove** [cwendt94/ff-espn-api#6]
Is it possible to add box scores to the API?  Then we could tabulate data on a points-per-player basis.  That would be very interesting.

**Comment by cwendt94** [comment]
That's a great idea! Looking through ESPN's API it looks like I can grab box scores with all the player data from 2018 and on. 

It seems they got rid of that data on seasons before 2018 so it would only work with seasons after 2017.

@ButteredGroove what were you thinking for structure and the data you would like to see?

My thoughts:
Have function that would get box scores for a certain week. It would return a list of match ups with the teams total score, players with projected and actual points and their roster position.

ESPN also breaks down how the players scored the points by yards, TD's, receptions, ect.. for both projected and actual points. This good be an added feature to the box score data break down.

With all this data you could really come up with some cool stats and player break downs!

**Comment by ButteredGroove** [comment]
@cwendt94 - that's perfect.  As far as roster position goes, if it includes who was on the bench, that could be informative too.  I could use that data to automatically generate what would have been the highest scoring lineup vs the actual lineup.  I'd also like to generate, for a team over the season, how many points players scored in their starting lineups ONLY.

**Comment by cwendt94** [comment]
Sure, I will put the teams full roster with all of the player information. I like the way you are thinking with all of this information!

I will start working on this feature soon!

**Comment by cwendt94** [comment]
@ButteredGroove I created a pull request with the added box score feature! Let me know what you think and it has the features you wanted!

**Comment by ButteredGroove** [comment]
I'll check it out tonight and tomorrow!  Ty!

**Comment by cwendt94** [comment]
Box scores is now added to the package

**Comment by ButteredGroove** [comment]
Got behind on my to-do list but I'm looking at it now and over the weekend.

**Comment by cwendt94** [comment]
No worries, looking forward to your feedback!

**Comment by ButteredGroove** [comment]
Very cool stuff!!!!  I'm digging it.

Though, one interesting tidbit... I'm seeing decimals to the hundredth's place for non-QBs, though their granularity goes only to a tenth of a percentage:
```
>>> box_scores[0].home_lineup[6]
Player(David Njoku, points:4, projected:12)
>>> box_scores[0].home_lineup[6].points
4.71

>>> box_scores[0].home_lineup[3]
Player(JuJu Smith-Schuster, points:10, projected:24)
>>> box_scores[0].home_lineup[3].points
10.94
```

Floating point fun?

**Comment by cwendt94** [comment]
For the decimal I can round that to tenth of a percentage. ESPN API gives the number with 16 decimal positions.

For the projected and regular points switching thanks for catching that! I see where it is doing that. I assumed ESPN was keeping a array order for projected and actual but it looks like they don't. I think I know the fix! I will start working on it soon!

**Comment by cwendt94** [comment]
The newest package should have those fixes!

**Comment by ButteredGroove** [comment]
Great!  Thanks for the fixes.  The projected vs actual points looks perfect!
I'm wondering if it's okay to leave decimals rounded to the hundredths place.  It's not uncommon for QBs to get .04 points per passing yard.  It depends on the league scoring situation.  Maybe it's best to leave the rounding decision to the calling code?  What do you think?

**Comment by ButteredGroove** [comment]
Sweet.  I just calculated how many starts, appearances on the bench, total points as a starter, and total points benched for each player on a per-team basis.  Love it!  And it's better than the no removed ESPN contributor page because it failed to list D/ST and kickers.  This has everything!

**Comment by cwendt94** [comment]
That's awesome! I am glad it has all the information you need! For the rounding, I think that's a good idea. We don't want to take away precision if some leagues use it!

**Comment by cwendt94** [comment]
The latest package uses two decimals. This feature should be good to close
