### ISSUE TITLE
box_player acquisition type

### ISSUE THREAD

**Issue by gayverjr** [cwendt94/ff-espn-api#69]
When a BoxPlayer object is constructed the acquisitionType is set to None. Is this fixable or just a problem in how the data is stored on ESPN's end?

**Comment by cwendt94** [comment]
I would have to check the data ESPN is sending. Which feature were you seeing this on? BoxScores?

**Comment by gayverjr** [comment]
Yep, BoxScores. Based on some half-assed print statement debugging, my suspicion is that it's an ESPN problem, but I would appreciate you looking into it if you have time because I'm sure you understand much better than I.

**Comment by cwendt94** [comment]
Yeah I can check out the data and see if ESPN is setting that data.

**Comment by cwendt94** [comment]
I just checked out the data ESPN API returns and for the players acquisitionType it is null. I do not know why they don't fill it out but it is indeed on ESPN's end.
