### ISSUE TITLE
Feature request: power rankings

### ISSUE THREAD

**Issue by dtcarls** [cwendt94/ff-espn-api#9]
Request to reimplement power rankings from espnff. 
https://github.com/rbarton65/espnff/blob/master/espnff/league.py#L82

I am the maintainer of https://github.com/dtcarls/ff_bot . I am transitioning to using your library since espnff seems abandoned and api v2 has gotten the axe.

**Comment by cwendt94** [comment]
Sure, I can add the power rankings feature. I was looking at ff_bot a little while ago and really like the idea. I am definitely going to use it for my league this year!

**Comment by cwendt94** [comment]
Power rankings is now in the most up to date package

**Comment by dtcarls** [comment]
Awesome thanks.
